! Rutherford Scattering Plot Scripts Generator
! This program generates scripts to view the results of simulations generated
! Rutherford Scattering Test Simulations program.
program rutherfhord_scattering_plot_scripts_generator

	use, intrinsic:: iso_fortran_env, only: stdin=>input_unit
	implicit none
	! Kind type parameters for increased real precision and integer length
	! Double precision reals, 15 digits, range 10**(-307) to 10**(307)-1; 64 bits
	integer, parameter :: dp = selected_real_kind(15, 307)
	! Long length for integers, range -2**63 to 2**63-1; 64 bits
	integer, parameter :: i8 = selected_int_kind(18)
	
integer(i8) :: NS, i, xy_scale, conserved_quantities_error, png_files
real(dp) :: hd
character(len=*), parameter :: input_file = "input.txt"
character(len=10) :: K0c, hdc, bc, dtc!AT MOST 10 CHARACTERS FOR INPUT VALUES!!!
character(len=:), allocatable :: K0ct, hdct, bct, dtct
character(len=:), allocatable :: base_file_name, data_file
character(len=:), allocatable :: script_file_t, script_file_ee, script_file_le
character(len=:), allocatable :: file_t, file_ee, file_le
integer(i8), parameter :: iu = 11, iun = 12	!Input file to read chars and NS
integer(i8), parameter :: ou_t = 13, ou_ee = 14, ou_le = 15!Output file, scripts

	print*, "Scattering Angle vs Step Size Automatic Plot Viewer (SAVSSA-PV)"
	print*, "This program generates scripts to view the results of simulations "
	print*, "generated by the SAVSSA program."
	print*

	print*, "*** AXES SCALE ***"
	print*, "1. Same scale in x and y axes"
	print*, "2. Scale fitting data"
	print "('Choose: ', $)"
	read*, xy_scale
	print*

	print*, "*** CONSERVED QUANTITIES ***"
	print*, "Open energy and angular momentum conservation error plots?"
	print*, "1. Yes"
	print*, "2. No"
	read*, conserved_quantities_error
	print*

	print*, "*** GENERATE IMAGE FILES ***"
	print*, "Generate png files for the plots?"
	print*, "1. Yes"
	print*, "2. No"
	read*, png_files
	print*
	!*****************************************************************************
	!Reading fixed parameters from input file using input character
	!Open input file twice: unit 11 to use as numbers, unit 12 to use as chars
	open(unit=iu, file=input_file, status='unknown')
	open(unit=iun, file=input_file, status='unknown')

	!Skip the first 5 lines of the input file
	do i=1,5
		read(iu, *)
		read(iun, *)
	end do

	!# of simulations/parameter sets, NS
	read(iu, *)
	read(iun, *) NS
	!# of points to be plotted, N
	read(iu, *)
	read(iun, *)
	!Initial kinetic energy, K0 [keV]
	read(iu, *) K0c
	K0ct = trim(K0c)
	read(iun, *)
	!Initial horizontal distance, hd [Å]
	read(iu, *) hdc
	hdct = trim(hdc)
	read(iun, *) hd
	hd = hd/0.5291772	! Conversion from Å to a0

	!Skip the next 4 lines of the input file
	do i=1,4
		read(iu, *)
	end do

!*******************************************************************************
	do i=1, NS
		!Reading variable parameters from input file
		!Impact parameter, b [Å]
		read(iu, *) bc
		bct = trim(bc)
		!Time step size, dt [aut]
		read(iu, *) dtc
		dtct = trim(dtc)

		!Naming data file to be used
		base_file_name = 'K0_'//K0ct//'keV_x0_'//hdct//'Å_b_'//bct//'Å_dt_'//dtct//'aut'
		data_file = base_file_name//'.dat'
		!Naming and opening script files to be written
		script_file_t = base_file_name//'_trajectories.gp'
		script_file_ee = base_file_name//'_energy_error.gp'
		script_file_le = base_file_name//'_ang_mom_error.gp'
		!Naming picture files to be written
		file_t = base_file_name//'_trajectories'
		file_ee = base_file_name//'_energy_error'
		file_le = base_file_name//'_ang_mom_error'

		open(unit=ou_t, file=script_file_t, status='unknown')
		open(unit=ou_ee, file=script_file_ee, status='unknown')
		open(unit=ou_le, file=script_file_le, status='unknown')

		!Simulation info to print in console
		print "('PLOT ', i3, ' OUT OF ', i3)", i, NS
		print*, 'K0: '//K0ct//'[keV], hd: '//hdct//'[Å], b: '//bct//'[Å], dt: '//dtct//'[aut]'

		!***************************************************************************
		!Writing the trajectories script
		write (ou_t, *) "set encoding iso_8859_1"
		if (png_files .eq. 1) then
			write (ou_t, *) "set terminal pngcairo size 14 in, 14 in"
			if (xy_scale .eq. 1) then
				write (ou_t, *) "set output '"//file_t//"_sq.png'"
			else
				write (ou_t, *) "set output '"//file_t//"_fit.png'"
			end if
		end if
		write (ou_t, *) "set title 'Electron-Electron Scattering'"
		write (ou_t, *) "set xlabel 'x [a0]'"
		write (ou_t, *) "set ylabel 'y [a0]'"
		write (ou_t, *) "set size square"
		!Setting plot scale
		if (xy_scale .eq. 1) then
!			hd = hd/0.5291772	! Conversion from Å to a0
			write (ou_t, *) "set xrange [-", hd, ":", hd, "]"
			write (ou_t, *) "set yrange [-", hd, ":", hd, "]"
		end if
		write (ou_t, *) "set grid"
		write (ou_t, *) "set xtics axis"
		write (ou_t, *) "set ytics axis"
		write (ou_t, *) "set clip two"
		write (ou_t, *) "f = '"//data_file//"'"
		write (ou_t, *) "plot f index 1 using 2:3 lc rgb 'blue' lt 1 lw 2 pt 7 ps 0.5 notitle with points, \"
		write (ou_t, *) "f index 0 using 1:2 lc rgb 'orange' lt 1 lw 2 pt 7 ps 1 notitle with lines"
		write (ou_t, *) "pause mouse button2"
		write (ou_t, *) "exit"

		close(ou_t)

		!***************************************************************************
		!Writing the energy percent error script
		write (ou_ee, *) "set encoding iso_8859_1"
		if (png_files .eq. 1) then
			write (ou_ee, *) "set terminal pngcairo size 14 in, 14 in"
			write (ou_ee, *) "set output '"//file_ee//".png'"
		end if
		write (ou_ee, *) "set title 'Percent Error in Energy'"
		write (ou_ee, *) "set xlabel 't [aut]'"
		write (ou_ee, *) "set ylabel 'Percent Error [%]'"
		write (ou_ee, *) "set size square"
		write (ou_ee, *) "set grid"
		write (ou_ee, *) "set xtics axis"
		write (ou_ee, *) "set ytics axis"
		write (ou_ee, *) "set clip two"
		write (ou_ee, *) "f = '"//data_file//"'"
		write (ou_ee, *) "plot f index 1 using 1:6 lc rgb 'green' lt 1 lw 2 pt 7 ps 0.5 notitle with lines"
		write (ou_ee, *) "pause mouse button2"
		write (ou_ee, *) "exit"

		close(ou_ee)

		!***************************************************************************
		!Writing the angular momentum percent error script
		write (ou_le, *) "set encoding iso_8859_1"
		if (png_files .eq. 1) then
			write (ou_le, *) "set terminal pngcairo size 14 in, 14 in"
			write (ou_le, *) "set output '"//file_le//".png'"
		end if
		write (ou_le, *) "set title 'Percent Error in Angular Momentum'"
		write (ou_le, *) "set xlabel 't [aut]'"
		write (ou_le, *) "set ylabel 'Percent Error [%]'"
		write (ou_le, *) "set size square"
		write (ou_le, *) "set grid"
		write (ou_le, *) "set xtics axis"
		write (ou_le, *) "set ytics axis"
		write (ou_le, *) "set clip two"
		write (ou_le, *) "f = '"//data_file//"'"
		write (ou_le, *) "plot f index 1 using 1:8 lc rgb 'purple' lt 1 lw 2 pt 7 ps 0.5 notitle with lines"
		write (ou_le, *) "pause mouse button2"
		write (ou_le, *) "exit"

		close(ou_le)

		!***************************************************************************
		!Opening the scripts
		call system ("gnuplot "//script_file_t)
		if (conserved_quantities_error .eq. 1) then
			call system ("gnuplot "//script_file_ee)
			call system ("gnuplot "//script_file_le)
		end if

		print*

	end do

	close(iu)
	close(iun)

end program